### ISSUE TITLE
Remove Kafka usage from the MQ example

### ISSUE THREAD

**Issue by TimMoore** [lagom/ibm-integration-examples#17]
I get an error about a port conflict with ZooKeeper when running the MQ example:

```
.....Exception in thread "main" java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:90)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:117)
	at org.apache.curator.test.TestingZooKeeperMain.runFromConfig(TestingZooKeeperMain.java:93)
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:148)
	at java.lang.Thread.run(Thread.java:748)
..Kafka Server closed unexpectedly.
```

It doesn't seem to be needed, so maybe we should remove the Kafka use from the example and disable it in the build.

**Comment by TimMoore** [comment]
It turns out that I did have another Kafka/ZooKeeper process running in the background that hadn't shut down cleanly from some previous `runAll`, so that explains the error.

Nonetheless, since Kafka isn't relevant to this example, it's still a good idea to trim it out.

**Comment by dwijnand** [comment]
Closing as stale.
